import { Inter } from "next/font/google";
import Layout from "../../components/Layout";
import Image from "next/image";
import Head from "next/head";
import styles from "../app/Home.module.scss";
import youtubeImg from "../../public/youtube.png";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export function generateMetadata() {
//   return {
//     title: "Next.js",
//   };
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <Layout>
            {children}
            {/* <Image src={youtubeImg} width={500} height={350} alt="preview" placeholder="blur" /> */}
          </Layout>
        }
      </body>
    </html>
  );
}
